# Generated by Django 3.0.8 on 2020-07-15 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20200715_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='photo',
            new_name='commented_photo',
        ),
    ]
