# Generated by Django 3.0.8 on 2020-07-15 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20200715_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commented_photo',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_owner',
            new_name='user',
        ),
    ]
